# Generated by Codex on 2026-07-31

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbershop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="break_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="barber",
            name="break_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="barber",
            name="work_days",
            field=models.CharField(default="0,1,2,3,4,5", max_length=20),
        ),
        migrations.AddField(
            model_name="barber",
            name="work_end",
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AddField(
            model_name="barber",
            name="work_start",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.CreateModel(
            name="BarberTimeBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("reason", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_blocks",
                        to="barbershop.barber",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(fields=["barber", "date", "start_time"], name="barbershop__barber__670194_idx"),
                    models.Index(fields=["is_active"], name="barbershop__is_acti_598dc1_idx"),
                ],
            },
        ),
    ]
